version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - notification-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notification-network

volumes:
  redis_data:

networks:
  notification-network:
    driver: bridge 